name: v2free_checkin
on:
  # schedule: 
  #   - cron: '* * * * *'
  workflow_dispatch:
jobs:
  v2free_checkin:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        shell: python
        env: 
          cookie: ${{ secrets.v2free_checkin_cookie }}
        run: |
          import requests
          url = 'https://w1.v2free.net/user/checkin'
          headers = {
            'Content-Type':'application/json',
            'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.62',
            'Accept-Encoding':'gzip, deflate, br'，
            'Cookie':os.environ['cookie']
          }
          res = requests.post(url = url, headers = headers)
          print(res.text)